networks:
  web:

services:
  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/Caddyfile:/etc/caddy/Caddyfile
      - ~/sites:/var/www
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web
    logging:
      driver: "local"
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - web
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: <admin password>
      MINIO_DOMAIN: minio.<my domain>.<tld>
      MINIO_SERVER_URL: https://minio.<my domain>.<tld>
    command: server --console-address ":9001" /data
  <planet name>:
    image: tloncorp/vere:latest
    restart: always
    # If you're going to host multiple ships, each ship will need to use
    # different ports.
    #
    # The HTTP port should map to a linearly increasing port number for each
    # successive ship (e.g. 8081, 8082, 8083, ...).
    #
    # The Ames port should be mapped to whatever port you want, that you listed
    # as needing to be opened in vps-setup.sh (e.g. 45454, 12121, ...). In
    # addition, the Ames port will also need to be explicitly set for each
    # ship after the first as part of the launch command. Note that this isn't
    # absolutely necessary, but it will GREATLY increase the networking
    # efficiency of your ship.
    #
    #   Example setup for a second ship
    # ports:
    #   - "8081:80"
    #   - "45454:45454/udp"
    # command: -p=45454
    ports:
      - "8080:80"
      - "34343:34343/udp"
    volumes:
      - <planet name>:/urbit
    networks:
      - web
    logging:
      driver: "local"
    # These used to work, but currently aren't. It's pretty annoying, as to do
    # troubleshooting, you need to either use the web terminal, or you need to
    # stop your ship, launch it manually without using docker compose, perform
    # troubleshooting, then exit and relaunch using docker compose.
    #
    # See:
    #
    # stdin_open: true
    # tty: true
    depends_on:
      - caddy
      - minio
  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: web-<planet-name>-1

volumes:
  caddy_data:
    external: true
  caddy_config:
    external: true
  <planet name>:
    external: true
  minio_storage: {}
