version: "3.8"

networks:
  web:

services:
  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/Caddyfile:/etc/caddy/Caddyfile
      - ~/sites:/var/www
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web
    logging:
      driver: "local"
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - web
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: <admin password>
      MINIO_DOMAIN: minio.<my domain>.<tld>
      MINIO_SERVER_URL: https://minio.<my domain>.<tld>
    command: server --console-address ":9001" /data
  <planet name>:
    # Using direct version numbers because sometimes latest is a Tlon-internal binary
    # See https://hub.docker.com/r/tloncorp/urbit
    image: tloncorp/urbit:v1.14
    restart: always
    ports:
      - "34343:34343/udp"
    volumes:
      - <planet name>:/urbit
    networks:
      - web
    logging:
      driver: "local"
    stdin_open: true
    tty: true
    depends_on:
      - caddy
      - minio
 
volumes:
  caddy_data:
    external: true
  caddy_config:
    external: true
  <planet name>:
    external: true
  minio_storage: {}
